server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cursomc?zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&verifyServerCertificate=false&useSSL=true&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
